### PR TITLE
Update Abstract_Cloth.html

### PR DESCRIPTION
**Pull request by HaroleDev**
Author name change (and yes, I was formerly named orcH) and I'd love to be displayed as Harole Ethan instead.

### CODE REVIEW

**Comment by t1m0thyj** [comment]
@HaroleDev This PR only changes your name as displayed on the website. If you want your name to be changed in the app as well, you'll need to update your theme's DDW file on MediaFire to change the name defined in the `imageCredits` property. Then I can rebuild the site, since all content is automatically generated from the JSON metadata in DDW theme files.

**Comment by HaroleDev** [comment]
Here it is as requested. https://www.mediafire.com/file/zlot4uiqpeb6t9d/Abstract_Cloth.ddw/file 
EDIT: Well I do apologize that I don't have the account on hand to update the file, for now, so you'll need to use the link I sent.

**Comment by t1m0thyj** [comment]
> Here it is as requested. https://www.mediafire.com/file/zlot4uiqpeb6t9d/Abstract_Cloth.ddw/file

The "imageCredits" property in the linked DDW still lists your old name.

**Comment by HaroleDev** [comment]
Whoops, hopefully, its metadata is updated with the same link now.

**Comment by HaroleDev** [comment]
So... any updates on the situation?

**Comment by t1m0thyj** [comment]
Thanks for updating the DDW file on MediaFire and sorry for the delay, should be fixed now in https://github.com/t1m0thyj/WDD-website/commit/bd812bd6205e2249ec4a0dd63b913a9268f3b96d

**Pull request closed without merging**
